added ability to add books to author
justin-obrien-smoothstack/lms-adm-node pull request #33
Opened 2020-05-29 17:43 UTC by sean-darsie

Added the ability to add books associated with an author to the relational table.

2020-05-29 20:54 UTC, justin-obrien-smoothstack requested changes
Looks good for the most part.

The DAO functions don't need to be async, since they're not using await.

The console.log calls should probably be removed, possibly replaced with calls to a logger such as winston.

Response messages and status codes should be set in the controller, not the service.

2020-05-29 20:54 UTC, justin-obrien-smoothstack commented on service/authorService.js
> +                        await authorDao.removeBookConnections(authorId);
This isn't needed when deleting the author, as long as foreign keys are set to cascade on deletion in the database (which I believe they are by default).

2020-05-29 20:54 UTC, justin-obrien-smoothstack commented on service/authorService.js
> +                    await authorDao.removeBookConnections(db, result.insertId);
This isn't needed when creating an author, since no author with the same primary key will have previously existed in the database.

2020-06-01 22:43 UTC, justin-obrien-smoothstack commented on sDao/branchDao.js
> +        db.query(sql,function(err,result) {
Don't forget to pass the parameters too!

2020-06-04 14:40 UTC, trevorhuis-smoothstack commented on controller/authorController.js
> +    console.log(req.body);
Are these console.log() for debugging or are they meant to remain in the application?

2020-06-04 14:42 UTC, trevorhuis-smoothstack commented on service/branchService.js
> +    return new Promise((resolve, reject) => {
This function is empty?

2020-06-04 14:42 UTC, trevorhuis-smoothstack requested changes
I am going to stop reviewing, looks like this pr is in middle of development.

2020-06-06 00:16 UTC, merged